### ISSUE TITLE
stopPlayback() method acts like pause for ExoPlayer

### ISSUE THREAD

**Issue by bkhall** [brianwernick/ExoMedia#105] opened 2016-02-15 14:50 UTC
The stopPlayback() method calls setPlayWhenReady(false) instead of exoplayer.stop().

The stop method should be called so that the player state will be set to STATE_IDLE.

The setPlayWhenReady method does not change the player state, so calling stopPlayback doesn't properly transition the player state.

**Comment by RedshirtMB** [comment] 2016-02-17 18:54
Hi Brian, just curious if your slating this for the version 3 release or if you're planning to knock this off in a 2.x release?  

I believe this is the cause of a bug I'm seeing in a project I'm close to releasing.

**Comment by brianwernick** [comment] 2016-02-17 19:08
I'll look in to it a little more to see if it would require architectural change.  If so then it will be in the 3.0 release, otherwise I can patch it in the 2.5 cycle.  I'll let you know (probably later tonight)

**Comment by brianwernick** [comment] 2016-02-18 00:46
I have updated the `stopPlayback()` methods to correctly call `stop()` in https://github.com/brianwernick/ExoMedia/commit/4f45881ebf156f7f3f3888421c639dcf75c35b1d. I'll try to get a release out in the next few days (I want to see if there are a few other issues I can resolve before then)

**Closed by brianwernick** 2016-02-18 00:46 UTC
Labels: bug

**Comment by RedshirtMB** [comment] 2016-02-21 21:39
Just tested this update did resolve the bug I was seeing. Thanks much.

**Comment by brianwernick** [comment] 2016-02-21 21:39
Good to hear :)
