### ISSUE TITLE
[Q] how to use VideoControlsMobile to skin 

### ISSUE THREAD

**Issue by riinav** [brianwernick/ExoMedia#213] opened 2016-05-25 07:25 UTC
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0-preview2`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
wrt #37 and #28, Can you setup a demo or add more info or a guide on how to skin the VideoControls, adding more buttons etc

how to use `EMVideoView.getVideoControls().addExtraView(view)`

an [SO](http://stackoverflow.com/questions/37013181/npe-when-extending-videocontrolsmobile-class) related to the above issue

An official guide would be much better to tackle this most common usecase

**Comment by brianwernick** [comment] 2016-05-26 17:22
I don't understand what you are asking for.  #28 is referencing an old architecture (pre 3.0) while #37 is referencing the new architecture.  Additionally the SO post linked is from #193.  Those alone with the documentation for 3.0 (when it is officially released) will handle those cases

**Comment by riinav** [comment] 2016-05-27 09:05
@brianwernick,

What I am trying to ask is How do we skin the default Video controls, for eg, 
`VideoControlsMobile` class handles the player and it's UI (like on touch display player control panel etc) . So how do we extend this class to add new functionality to it. let's say we want to add few buttons to the player control like mute, full screen mode etc.

also, how do we change the drawables for default icons on player for play, pause etc

`VideoControlsMobile` class is from new 3.0 architecture, which currently is in preview, so is it possible for you to add some tips or documentation on how to use this class to skin the player

Sorry, if I am still confusing you

**Comment by brianwernick** [comment] 2016-05-27 15:30
There are a few areas you asked about so I will break it down by those.

**Changing the icons**
You don't need to override the `VideoControls` to specify custom icons, you can call one of the `*ImageResource` methods (e.g. `setPreviousImageResource(...)`).  However if you want to do a complete change to them (or are already extending the class) you can override `updateButtonDrawables()`

**Adding Buttons**
As you pointed out there is the `addExtraView(view)` method in the `VideoControls` if you just want a quick way to add extra views.  This method essentially acts like a normal `LinearLayout` (next to the end time field)

**Skinning**
This is pretty broad and will change depending on the use case, but in general you can do two things:

1. Override the layout resource (create a duplicate of the same name) and update the styling to how you like.  A down side to doing this is any modifications I make in the future (to the layout) would need to be pulled in manually (or maybe this is an advantage, it depends on what you want)
2. Extend the `VideoControlsMobile` and/or `VideoControlsLeanback` and change the styling (colors?) there as needed.

**General**
One of the things you mentioned is adding tips or documentation for this type of thing.  The documentation is nearly complete for the 3.0 release, there are a few methods I still need to update/add, but the main point of those is to note what the methods do, when to use them, and sometimes why they are called.  On that note, this is something that should be added to the Wiki, which I've wanted to create for some time now but was waiting for 3.0 to release first.

**Closed** 2016-05-29 15:35 UTC
Labels: Question
