### ISSUE TITLE
Accessing STATE_BUFFERING 

### ISSUE THREAD

**Issue by martinsce** [brianwernick/ExoMedia#457] opened 2017-05-20 14:36 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.1`

Is it possible to get STATE_BUFFERING updates in ExoMedia without forking the repo? See comments about using it in  https://github.com/brianwernick/ExoMedia/issues/102

Sometimes live streams stall for quite some time without receiving onError so it would be very useful.

**Comment by brianwernick** [comment] 2017-05-22 14:28
You even linked the issue this is a duplicate of, so I'm not sure why you created the issue

**Closed by brianwernick** 2017-05-22 14:28 UTC
Labels: Duplicate
