### ISSUE TITLE
Video is not played (by seek to 0:00) after completion

### ISSUE THREAD

**Issue by ypresto** [brianwernick/ExoMedia#260] opened 2016-06-26 16:11 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 5X`

###### Reproduction Steps
 0.  Start playing video with EMVideoView.
 0.  Play through end of the video and black screen is shown.
 0.  Seek to 0:00 with EMVideoView's default controll.

###### Expected Result
Start playing video from beginning.

###### Actual Result
Stall at ProgressBar and black screen, video is not played.

###### Related issues
- #116
- #112

**Comment by brianwernick** [comment] 2016-06-26 17:22
Duplicate of #238

**Closed by brianwernick** 2016-06-26 17:22 UTC
Labels: Duplicate
