### ISSUE TITLE
Fire TV Support?

### ISSUE THREAD

**Issue by ebr11** [brianwernick/ExoMedia#161] opened 2016-04-06 17:55 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.6`
 - Device OS version: `5.1`
 - Devide Manufacturer: `Amazon`
 - Device Name: `Fire TV`
 
Do you have any plans to include support for the Fire TV by utilizing the [Amazon exo port](https://github.com/amzn/exoplayer-amazon-port)?

**Comment by brianwernick** [comment] 2016-04-06 18:20
I don't currently have any plans for supporting this, however It may be something to look in to as an extension library in the future.  
Without looking in to the library, I'm assuming that it would be relatively simple (not necessarily quick) to swap out the ExoPlayer implementations in the 3.0 branch.

**Comment by se-bastiaan** [comment] 2016-04-06 18:50
They do not seem to provide it as a maven dependency though.

**Comment by ebr11** [comment] 2016-04-06 18:51
Yeah, I couldn't find it on maven either, but I was able to clone their project, build it, and then replace the dependency in ExoMedia with a local jar and everything appears to build properly...

**Comment by brianwernick** [comment] 2016-04-06 18:51
That may be the first step towards implementing it then; request they publish it to `mavenCentral` or `jcenter`.

**Comment by se-bastiaan** [comment] 2016-04-06 19:07
https://github.com/amzn/exoplayer-amazon-port/issues/2

**Comment by ebr11** [comment] 2016-04-06 20:12
Yeah, I don't think this will be that hard to accomplish.  I just got playback to work with the above customization plus removing "Amazon" from the non-compliant devices list and also modifying the isDeviceTV method to account for the Fire (which is only on 5.1).

I hope you will consider it if they make it easy to include their version of Exo.  Thanks.

**Comment by brianwernick** [comment] 2016-04-06 20:36
It comes down to a few details which will indicate how simple it is to add:
1. What will the architecture of the `EMExoPlayer` look like to allow swapping between the `ExoPlayer` and the `AmazonExoPlayer`?
2. Does the `AmazonExoPlayer` support everything the `ExoPlayer` does plus Amazon devices?
3. (depends on `2`) Should `ExoMedia` depend on both, or should there be an extension library that will override the `ExoPlayer` implementation to use the `AmazonExoPlayer` for just Amazon devices

These are just my concerns / questions more to keep track of them, they aren't really directed at anyone in particular.

**Comment by ebr11** [comment] 2016-04-06 20:52
I understand.  For your information, the Amazon port appears to be method compatible with the Google version.

In other words, I don't think you will need to make any architectural changes but, rather, just have two build flavors - one that references the Google version and one that references the Amazon one - and then just make any modifications like the ones I did above to account for the fact that the Amazon device should now use the actual ExoPlayer instead of fall back to the VideoView.

Of course, there could be more gotchas somewhere under the surface.  The devil is always in the details...

**Comment by se-bastiaan** [comment] 2016-04-06 20:53
The Amazon project currently uses the same package as the main ExoPlayer project does so it's pretty much impossible to mix the two.

**Comment by ebr11** [comment] 2016-04-12 00:21
I'm looking at basing my mods on the 3.0 branch to get some of the other goodies you've put in there.

What happened to setOnProgressCallback in the EmAudioPlayer?  Are you removing that or are changes just in-progress?

**Comment by brianwernick** [comment] 2016-04-12 14:17
The progress polling was purposefully removed from 3.0 as is was only intended for the playlist support (which as been pulled in to it's own library [PlaylistCore](https://github.com/brianwernick/PlaylistCore))

**Comment by brianwernick** [comment] 2016-05-31 17:56
I've updated the checks to determine if devices support the ExoPlayer which means any FireOS 5+ device should be using the ExoPlayer now.  That, in addition to no questions being answered on that branch tells me this is about as close as we are going to get.  As such I'm going to close this

**Closed** 2016-05-31 19:13 UTC
Labels: Feature Request, Won't Fix

**Comment by peddisri** [comment] 2017-08-24 09:02
We (Amazon) have published the libs to jcenter.
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-core
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-hls
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-ui
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-smoothstreaming
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-dash

Please note that the patches done on top of Google's version are targeted to specific Amazon device models.  They will be no-op on other devices. We have tried to do our best not to let our patches impact non-amazon devices. 

So you can actually use Amazon's port of Exoplayer on other devices too. In case you find regressions caused due to one of our patches, please log an issue in the github.
