### ISSUE TITLE
reset the bitrate when setvideoURI a new playlist?

### ISSUE THREAD

**Issue by jboisjo** [brianwernick/ExoMedia#470] opened 2017-06-05 00:44 UTC
Hey Brian!

Sorry to bug you again with that issue, but is there a way that i can reset the bitrate manually when i'm setting a new playlist? On 3.0.1 it was like this, but its saving his bitrate since 4.0.

Thanks alot ;)

**Comment by brianwernick** [comment] 2017-06-05 14:10
Currently there is no way to reset the discovered bandwidth. And again, I'm not sure why you would want to (for others this is related to #461)

**Comment by jboisjo** [comment] 2017-06-06 13:54
i was using the version 3.1.1 and when i insert a new playlist and play it, bitrate is reset. But now, since version 4.0.0 it saves it and cause couple problems on couple devices, like flickering, skipping frames...

**Comment by brianwernick** [comment] 2017-06-06 14:12
Are you sure it's the bandwidth stuff that's causing the flickering and dropped frames?

**Comment by jboisjo** [comment] 2017-06-06 15:05
well, when it change his resolution in the m3u8 files, its flickering to resize the window. So my guess  is that it starts the lowest but get the highest right away when flicker when resize the resolution

**Comment by jboisjo** [comment] 2017-06-06 15:07
as soon as i put useSurfaceViewBacking="true" it flickers everywhere in 3.0.0 but quality is the best but really annoying when it flickers.

**Comment by brianwernick** [comment] 2017-06-06 15:57
Oh, do you mean it just flickers initially (not continuously?) cause then that would be under #326. But yeah, until that is fixed you can see if the `useTextureViewBacking="true"` in 4.0 fixes it.

**Comment by jboisjo** [comment] 2017-06-08 23:56
yes exactly, it flickers initially not continuously! but its weird that in 3.1.1 it was resetting everytime and not in the latest version :(

**Comment by brianwernick** [comment] 2017-06-09 14:40
I'm going to close this as a duplicate of #326 then. 

As far as the bandwidth goes, It's an optimization of the library to keep the determined bandwidth between playable items instead of resetting (like `3.x` did)

**Closed by brianwernick** 2017-06-09 14:40 UTC
