### ISSUE TITLE
wake locks set by setWakeMode() are ignored 

### ISSUE THREAD

**Issue by nordfalk** [brianwernick/ExoMedia#24] opened 2015-10-13 14:30 UTC
Current version of EMExoPlayer.java isnr aqquiring and releasing the wake lock specified by setWakeMode(), so effectively  wake locks set by setWakeMode() are ignored.

https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/exoplayer/EMExoPlayer.java

Have a look at the Android MediaPlayer source. You need to have a funkction like

    private void stayAwake(boolean awake) {
        if (mWakeLock != null) {
            if (awake && !mWakeLock.isHeld()) {
                mWakeLock.acquire();
            } else if (!awake && mWakeLock.isHeld()) {
                mWakeLock.release();
            }
        }
        mStayAwake = awake;
        updateSurfaceScreenOn();
    }

and add calls to stayAwake() in start(), stop() etc.

**Comment by brianwernick** [comment] 2015-10-29 20:04
So I'm not sure what the issue is.  There is https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/EMAudioPlayer.java#L335 which interacts with https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/exoplayer/EMExoPlayer.java#L325

**Comment by nordfalk** [comment] 2015-10-31 12:57
Its fine that EMAudioPlayer.java interacts with EMExoPlayer.java, but EMExoPlayer.java is doing *nothing* with its wakelock! 

The variable is simply never been used outside if the method!!

I dont want to repeat post #1 again. ... but If you can't see for yourself that wakeLock is never used, then try to monitor the wake locks with
adb shell dumpsys power 
and you will notice that no wake lock is being taken.

If you'd like to se an example of code that actually uses the wake lock, have a look at
https://github.com/androidlundogbendsen/dr-radio-android/blob/master/DRRadiov35/app/src/main/java/dk/dr/radio/afspilning/wrapper/EmaPlayerWrapper.java

**Comment by brianwernick** [comment] 2015-11-06 23:14
OK, sorry it took me so long to get back to you; I've been pretty busy the last few weeks.  When I last looked at it I must have misunderstood what you were saying.  I have now updated the source to correctly acquire/release the wake lock when playback state changes (in the EMExoPlayer).  These changes will be in the next release (hopefully this weekend)

**Closed** 2015-11-06 23:14 UTC
Labels: bug
