### ISSUE TITLE
could you please add a setCaptionListener in ExoVideoView.java

### ISSUE THREAD

**Issue by zengxin** [brianwernick/ExoMedia#297] opened 2016-08-18 05:36 UTC
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0.  

###### Expected Result
Could you please add the following function in ExoVideoView.java? 
So that I can use it to support Closed Caption
Thanks

    public void setCaptionListener(CaptionListener captionListener) {
        this.captionListener = captionListener;
        emExoPlayer.setCaptionListener(captionListener);
    }

**Comment by brianwernick** [comment] 2016-08-18 14:13
Duplicate of #115

**Closed by brianwernick** 2016-08-18 14:13 UTC
Labels: Duplicate, Feature Request
