### ISSUE TITLE
Disabling Video Controls 

### ISSUE THREAD

**Issue by MarkedWarrior** [brianwernick/ExoMedia#236] opened 2016-06-08 17:42 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `4.4`
 
Hi, 
I love this library and I'm in the process of using it in my app as I am making a live tv streamer for android tv receivers. I am wondering if there is anyway to disable the player controls? I have set EMVideoView:useDefaultControls="false" which gets rid of the UI of the player such as the seek bar but every time I click on the player it pauses the stream. Is there anyway I can disable every control of the player? 

Thank you and I hope you continue adding to this library!

**Comment by brianwernick** [comment] 2016-06-08 20:27
The VideoView itself doesn't listen to touch events for controls, that is left to the `VideoControls`.  Since you aren't using those it shouldn't be pausing the stream; however to verify I tried removing the `VideoControls` from the demo app and was unable to control playback just by clicking on the view.

Have you specified any additional listeners on the `EMVideoView`?

**Comment by MarkedWarrior** [comment] 2016-06-09 17:50
Thank you for the quick reply!
I have only set a setOnPreparedListener and a setOnErrorListener. I forgot to mention in the question that I am not interacting with the player via touch but instead I'm interacting with it via onKeyUp/onKeyDown. I am using a remote (like a TV remote) to control the app/video player.

Thank you again!

**Comment by brianwernick** [comment] 2016-06-09 20:32
Oh, that might be the difference.  I'll have to try with a controller when I get a chance (I believe I have one to test with at home).  Of course, if you happen to find the issue I'm always open to PRs

**Comment by MarkedWarrior** [comment] 2016-06-10 04:39
Thank you! I'll try my best to solve it! I hope to hear from you soon!

**Comment by MarkedWarrior** [comment] 2016-06-10 21:16
So, I solved the bug with a simple - android:focusable="true" in the XML under the EMVideoView section. 

`<com.devbrackets.android.exomedia.ui.widget.EMVideoView`
        `    android:id="@+id/video_view"`
        `    android:layout_width="match_parent"`
        `    android:layout_height="match_parent"`
        `    EMVideoView:useDefaultControls="false"`
      ` android:focusable="true"/>`

**Comment by brianwernick** [comment] 2016-06-11 20:44
Because you have a workaround and because I still cannot reproduce it (even with a remote) I'm going to close this

**Closed by brianwernick** 2016-06-11 20:44 UTC
Labels: Bug
