### ISSUE TITLE
Offline DRM Widevine Secured Video Playback

### ISSUE THREAD

**Issue by nosmirck** [brianwernick/ExoMedia#445] opened 2017-05-08 17:30 UTC
_I'm not filling the template because my question is not related to any bug or problem._

Hi, I really appreciate that you took the time to write this wrapper, it's really good and easy to use and understand, the ExoPlayer demo is not something easy to understand, however, I have a couple of questions, if you can't help me with this I'll understand.

First, I have a secured DRM video, the URL is an mpd that has inside a segmented dash video.
Second, I have a license URL to play this video. Everything works fine when I use it as standard playback.

Now, I'm requested to provide Offline playback, I mean, download the video, save it on the device (with the license) and play the video in offline mode (no internet access).

Can anyone please provide a sample on how to achieve this?

Thank you in advance!

**Comment by brianwernick** [comment] 2017-05-08 20:13
It seems that you have already asked this in the more appropriate ExoPlayer question [949](https://github.com/google/ExoPlayer/issues/949). Because any response you get will be dependent on ExoPlayer implementation details I'm closing this in favor of that one

**Closed by brianwernick** 2017-05-08 20:13 UTC

**Comment by hungamademo** [comment] 2017-08-22 12:46
Hi,

We are trying to play Offline DRM Video(.mpd formated) Encoded with Widevine(Secure Expressplay URL). Here, We are able to download all files encoded with Widevine URL And We are able to play offline movie-files with having internet active.

We already reviewed "ExoPlayer question 949" but it's not working for us.

Here we are facing issues when trying to play video offline. It is giving DRM key error even if we have DRM byte[] key saved offline. 

We have two case while Playing Offline DRM Video.

Case 1: It's require internet to validate key. After that, It works fine without internet.
Is internet required to start up offline DRM video?

Case 2: We have stored .Mpd content/licence url/Server Token(in byte[]) for first time play. Now, I turned Internet OFF and Trying to play video with using locally stored licence URL, Token etc. Its giving me below error.

License URL:
https://wv.service.expressplay.com/hms/wv/rights/?ExpressPlayToken=AwAAAA9JKcQAAABgloeIqT9-w32YGm68zZMg59rymJ6D8Wp-iQCKg8vwvTDm32M35DS_yIDXW6fh5Cepz8bcI36AgBd6JLlFgeNu70nga6BCdWDpwZx2URPrWZcoajkhQzExzMyJ3B1hDb89yZyNhXOMLBQGYvqRJh92Hh2p1rc

Token:
CAIS4wIKSgogRjU0RUNEMjNENEFGQ0Q3NzAyMDAwMDAwMDAwMDAwMDASIEY1NEVDRDIzRDRBRkNENzcwMjAwMDAwMDAwMDAwMDAwGgAgASgAEgoIARAAGAEoADAAGmYSEMQyKwhe0wStPbolYjiugFgaUFtPn4xDINtJl3Qxf2Zrrw/FUd6e6JVb56XQxNUG/2TO/nGO4i5ADLCIP6ONYSp7agIXLWs1a2r35t7xP9mZE2+MCuPHwh3EXHIIrFLgjiurIAEaigEKEKAtDoupoYAqOKD+4fWuskMSEOENjDggeGY7NN/ukBhIcTYaIGbO88Z2EpoBq7QFcmKnd+BywwukmeKmgGieLe4U9EqaIAIoATIECAAQKkI0CiAPYHGbB2U8HlB9hswCJlOVzG6i7ng8BqmE538mQCZ7rxIQLGg/ojBEPDMEqgbR2Leq2WICSEQg87rwzAU4AEIMSERDUERBVEEAAAADGiCC9IZ+/iyp5/qp0X3u/GNw5hj0MGCBT1qi0egfjOJFmiKAAmtoU01zoFZz4i5Zl1v1zCz0Ih7xtympVAjmh/0uV+3EF8PYwvgX+3PBgv9Jeo8lEC2PxdOfuz8YYw28K8327rtxIgQJ9CpUjF+hr1yr+EFFOm4dJ5cUFPS4rdVRQDUEtcY6ebKz7P60X2IviS2WLpONdPJajBz7iCHuChEjZyC0VHrHbMUTH3jrvEEf7TGlLCEoIbNpJEEU4ICmJmZHU1Mw9XRvldgwvgpXZeKJ5fJ9xSHBRyCUbXbh8Xa4NunvpZ3hk8/2+P8Cm8/Wjx/oT1Jd1eLnt8YXEc5IWOyRy9URXtQDv6kSaKp/OSQDcF7U2t3ZSnQ7IZww2H/EAULzwVA=


========================== Log ==========================
08-22 17:00:56.337 30070-28717/com.google.android.exoplayer2.demo E/MediaDrm-JNI: Illegal state exception: Failed to restore keys: DRM vendor-defined error: -2949 (-2949)
08-22 17:00:56.338 30070-28717/com.google.android.exoplayer2.demo E/OfflineDrmSessionMngr: Error trying to restore Widevine keys.
                                                                                           android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: DRM vendor-defined error: -2949
                                                                                               at android.media.MediaDrm.restoreKeys(Native Method)
                                                                                               at com.google.android.exoplayer2.drm.FrameworkMediaDrm.restoreKeys(FrameworkMediaDrm.java:138)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.restoreKeys(DefaultDrmSessionManager.java:527)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.doLicense(DefaultDrmSessionManager.java:484)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:432)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:354)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748)
                                                                                               at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:213)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:501)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                               at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
08-22 17:00:56.339 30070-28717/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Renderer error.
                                                                                           com.google.android.exoplayer2.ExoPlaybackException
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:302)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:770)
                                                                                               at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:213)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:501)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                               at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                            Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: DRM vendor-defined error: -2949
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onError(DefaultDrmSessionManager.java:611)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.restoreKeys(DefaultDrmSessionManager.java:531)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.doLicense(DefaultDrmSessionManager.java:484)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:432)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:354)
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748)
                                                                                               at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:213) 
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:501) 
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                               at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                                            Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: DRM vendor-defined error: -2949
                                                                                               at android.media.MediaDrm.restoreKeys(Native Method)
                                                                                               at com.google.android.exoplayer2.drm.FrameworkMediaDrm.restoreKeys(FrameworkMediaDrm.java:138)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.restoreKeys(DefaultDrmSessionManager.java:527)
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.doLicense(DefaultDrmSessionManager.java:484) 
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:432) 
                                                                                               at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:354) 
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748) 
                                                                                               at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:213) 
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:501) 
                                                                                               at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464) 
                                                                                               at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                                               at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                               at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
08-22 17:00:56.350 30070-30070/com.google.android.exoplayer2.demo E/EventLogger: playerFailed [5.64]
                                                                                 com.google.android.exoplayer2.ExoPlaybackException
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:302)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:770)
                                                                                     at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:213)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:501)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                  Caused by: com.google.android.exoplayer2.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: DRM vendor-defined error: -2949
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.onError(DefaultDrmSessionManager.java:611)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.restoreKeys(DefaultDrmSessionManager.java:531)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.doLicense(DefaultDrmSessionManager.java:484)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:432)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:354)
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748)
                                                                                     at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:213) 
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:501) 
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                                  Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: DRM vendor-defined error: -2949
                                                                                     at android.media.MediaDrm.restoreKeys(Native Method)
                                                                                     at com.google.android.exoplayer2.drm.FrameworkMediaDrm.restoreKeys(FrameworkMediaDrm.java:138)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.restoreKeys(DefaultDrmSessionManager.java:527)
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.doLicense(DefaultDrmSessionManager.java:484) 
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.openInternal(DefaultDrmSessionManager.java:432) 
                                                                                     at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:354) 
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:748) 
                                                                                     at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:213) 
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:501) 
                                                                                     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464) 
                                                                                     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                     at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 

We need help to fix this issue. Anyone have solution for this issue. Please suggest us.

Thanks,
Kautik Patel

**Comment by Prashast09** [comment] 2019-01-29 08:06
Hey @HungamaSurat were you able to solve this issue? Or has anyone else?

**Comment by CanePro612** [comment] 2020-11-09 10:15
Has anyone solved this issue? 
Steps: 
1. Download the DRM protected content 
2. Download the offline licence with OfflineLicenceHelper
3. Remove the internet connection (go to offline mode) 
4. Play the content without an internet connection with offline licence valid to a month time

Netflix and other apps are doing it ... why is this so hard to explain?

**Comment by J6ey** [comment] 2021-05-05 20:51
I also get `Failed to restore keys: DRM vendor-defined error: -2949` when playing an offline content on an actual device, however, the offline streaming works on all Android emulators. Isn't that bizarre?

**Comment by J6ey** [comment] 2021-07-13 22:57
@HungamaSurat
@Prashast09 
@CanePro612 
Hi again, kinda late but still looks like a ongoing issue for some. Here [8691](https://github.com/google/ExoPlayer/issues/8691#issuecomment-879455043) is how fixed my offline streaming issue throwing "Failed to restore keys".
