### ISSUE TITLE
setVideoPat http stream VideoQuality Low

### ISSUE THREAD

**Issue by ronovar** [brianwernick/ExoMedia#205] opened 2016-05-16 13:38 UTC
I have:

- ExoMedia version: 2.5.6
- Device OS version: 4.4.2
- Device Manufacturer: Strong
- Device Name: Strong

using: setVideoPat i set URL of stream and then i call start().

Video is playing, but picture quality is low...what is the api function in ExoMedia jar file that i need to call to set up middle or high quality video?

In vlc on PC stream video is perfect...source is high quality ( bandwidth is from 1,5 to 2,0mbit/s)

**Comment by brianwernick** [comment] 2016-05-16 14:28
Are you talking about an HLS URL?  If that's the case then the ExoPlayer is following the standardization and using the first url specified in the m3u url.  If you want a better quality to be used initially then you can either update the m3u ordering or you can specify your own HLS `RenderBuilder`

As a note: This is something I would like to optimized (as it currently takes about 10-15 seconds to update)

**Comment by ronovar** [comment] 2016-05-16 14:57
Thanks for answering..could you please give me example? Or page where is examle? I im using ExoMedia.jar wrapper and it is excellent....i im searching in jar api functions about rended builder but could not find one...do i need to write my own public class that calls RenderBuilder?

**Comment by brianwernick** [comment] 2016-05-16 15:02
You can look at [EMVideoView#L329](https://github.com/brianwernick/ExoMedia/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fdevbrackets%2Fandroid%2Fexomedia%2Fui%2Fwidget%2FEMVideoView.java#L329) for the function to call and [ExoVideoView#L264](https://github.com/brianwernick/ExoMedia/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fdevbrackets%2Fandroid%2Fexomedia%2Fcore%2Fvideo%2FExoVideoView.java#L264) to see how it currently determines the RenderBuilder to use

**Comment by ronovar** [comment] 2016-05-16 22:06
I read above example and i get this:

public void SetVideoURI(String URI) {
		Uri uri = Uri.parse(URI);
		((EMVideoView)getObject()).setVideoURI(uri, ((EMVideoView)getObject()).getRendererBuilder(MediaSourceType.DEFAULT, uri, MediaUtil.MediaType.TS));
	}

But eclipse give me 1 error:

Description	Resource	Path	Location	Type
The method getRendererBuilder(MediaSourceType, Uri, MediaUtil.MediaType) from the type EMVideoView is not visible	ExoPlayer.java	/google.b4a.exoplayer/src/google/b4a/exoplayer	line 190	Java Problem

How to fix this errr EMVideoView is not visible?

**Comment by brianwernick** [comment] 2016-05-16 22:20
I should have noted this is with the 3.0 preview build.  The process is quite a bit more complex in the 2.5 releases

**Comment by ronovar** [comment] 2016-05-16 22:28
Ok...so what you suggest? Could i try 3.0 preview build? And where is it if is public? I see in eclipse that getRenderBuilder is private function not public...that is reason why is not public.

Thanks for helping me out...i will try 3,0 preview build if is available to download from git or what is release date?

**Comment by ronovar** [comment] 2016-05-16 22:43
I downloaded 3.0.0-preview1 and see that is all code changed...so i need to ask in what package is function getRendererBuilder? In 2.5.6 it was in com.devbrackets.android.exomedia.EMVideoView

**Comment by ronovar** [comment] 2016-05-16 22:45
I downloaded 3.0.0 preview-1 build and start to call this function getRenderBuilder...will post result...

**Comment by brianwernick** [comment] 2016-05-16 23:51
It seem I forgot that the ability to specify a `RenderBuilder` was added in a 2.5 release ([EMVideoView#L819](https://github.com/brianwernick/ExoMedia/blob/2.5.6/library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java#L819)).  However because there won't be any more 2.x releases you will need to override [setVideoURI(Uri uri, MediaUtil.MediaType defaultMediaType)](https://github.com/brianwernick/ExoMedia/blob/2.5.6/library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java#L804) and duplicate the `getRenderBuilder()` method for your own use.

As a note: in 3.0 the `getRenderBuilder()` function is `protected` so you would be able to access it by extending the `ExoVideoView`

**Comment by ronovar** [comment] 2016-05-17 07:57
Ok..i will now switch to 3.0.0 library and will port old code from jar to new version. In 2.5.6 version i defined listener like this:

@Override
	@BA.Hide
	public void innerInitialize(final BA pBA, final String pEventName, boolean pKeepOldObject)
	{
		if (!pKeepOldObject)
	    {
	    	EMVideoView VideoView = new EMVideoView(pBA.context);
	    	
	    	/*
	    	 * OnCompleted Event
	    	 * Called when the end of a media source is reached during playback
	    	 */
	    	if (pBA.subExists(pEventName + "_oncompleted")) {
	    		VideoView.setOnCompletionListener(new MediaPlayer.OnCompletionListener()
	    		{
	    			@Override
	    			public void onCompletion(MediaPlayer mp)
	    	        {
	    	            pBA.raiseEvent(ExoPlayer.this, pEventName + "_oncompleted", new Object[0]);
	    	        }
	    	    });
	        }
}

Now i could not get point how can i define oncomplete listener for version 3.0.0. i try:
VideoView.setOnCompletionListener(new MediaPlayer.OnCompletionListener() but eclipse make an error...could you please write how can i set setOnCompletionListener so that i can port existing events on same way.

Thanks.

**Comment by ronovar** [comment] 2016-05-17 12:14
And if you can please give example code how to call and set up getRenderBuilder() in new version 3,0,0...thanks.

**Comment by brianwernick** [comment] 2016-05-17 14:11
In 3.0 the `OnCompletionListener` isn't the `MediaPlayer.OnCompletionListener` instead it is one packaged in the library (the other media listeners are the same, such as the `OnPreparedListener`).  

I'm not quite sure what you are asking for with the getRenderBuilder setup. If you are asking what the HlsRenderBuilder that you create will look like (essentially a duplicate of the `HlsRenderBuilder` packaged with ExoMedia) then I believe you will just need to create your own `HlsTrackSelector` (see [HlsRenderBuilder#L170](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/builder/HlsRenderBuilder.java#L170))

**Comment by ronovar** [comment] 2016-05-17 14:38
Ok...i need to describe problem more detail:

I have this code to play url stream (http://myurl/channelname) and the stream is h.264 iptv channel.

I use this code to play video:

public void SetVideoURI(String URI) {
		Uri uri = Uri.parse(URI);
		((EMVideoView)getObject()).setVideoURI(uri);
	}

and it plays iptv channel but video is low quality...and iptv channel on pc vlc is hiqh quality...so my question is how can i setup exoplayer to play high quality iptv channel?

You say that i need to use RenderBuilder but i don't know how i need to call it..so if you can please share here example code how to setVideoURI and set high quality video play from http stream.

**Comment by brianwernick** [comment] 2016-05-17 15:22
Assuming `3.0`

instead of calling `setVideoUri(videoUri);` you should call `setVideoUri(videoUri, getRenderBuilder(MediaSourceType.get(uri), uri));` where `getRenderBuilder(...)` will be your own function (inside a util or your fragment/activity) that mimics the above `getRenderBuilder()` method.

However, your implementation will look more like 
```java
    protected RenderBuilder getRendererBuilder(MediaSourceType renderType, Uri uri) {
        switch (renderType) {
            case HLS:  //NOTE: this is your modified HlsRenderBuilder that customizes the HlsTrackSelector
                return new CustomHlsRenderBuilder(getContext().getApplicationContext(), getUserAgent(), uri.toString());
            case DASH:
                return new DashRenderBuilder(getContext().getApplicationContext(), getUserAgent(), uri.toString());
            case SMOOTH_STREAM:
                return new SmoothStreamRenderBuilder(getContext().getApplicationContext(), getUserAgent(), uri.toString());
            default:
                return new RenderBuilder(getContext().getApplicationContext(), getUserAgent(), uri.toString());
        }
    }
```

**Comment by ronovar** [comment] 2016-05-17 15:47
Thanks...i im using 3,0 but i im getting in eclipse error that Description	Resource	Path	Location	Type
SmoothStreamRenderBuilder cannot be resolved to a type	ExoPlayer.java	/google.b4a.exoplayer/src/google/b4a/exoplayer	line 57	Java Problem
 
I think it will be good way if you please could upload here zipped java project(android) that calls function 
setVideoUri(videoUri, getRenderBuilder(MediaSourceType.get(uri), uri));

this way i then open your example file...compile java source and enter url of stream...and then i will learn how to call this function.

Please if you have time create example with setVideoUri that accepts http url of iptv stream and set SmoothStreamRenderBuilder,

Thanks

**Closed** 2016-05-20 00:18 UTC
Labels: Question
