### ISSUE TITLE
can't watch the video but I can hear the sound

### ISSUE THREAD

**Issue by bkjbkjbnkj687698698** [brianwernick/ExoMedia#97] opened 2016-02-10 15:10 UTC
The issue is that i can't watch the video but I can hear the sound.I am playing videos inside gridview.Below is code I am using-

Adapter-

   

    public class GridAdapter extends BaseAdapter {
  
        @Override
        public View getView(final int position, View convertView, ViewGroup parent) {
            final Context context = parent.getContext();
    
            VideoViewHolder viewHolder = null;
            if (convertView == null) {
                LayoutInflater layoutInflater = LayoutInflater.from(context);
                convertView = layoutInflater.inflate(R.layout.item_pagergrid, null);
                viewHolder = new VideoViewHolder();
     
                viewHolder.emVideoView = (EMVideoView)convertView.findViewById(R.id.exovideoview);
                convertView.setTag(viewHolder);
            } else {
                viewHolder = (VideoViewHolder) convertView.getTag();
            }
        final VideoViewHolder holder=viewHolder;
    
    holder.emVideoView.bringToFront();
    holder.emVideoView.setMinimumWidth(width);
    holder.emVideoView.setMinimumHeight(height);
    holder.emVideoView.setVideoURI(Uri.parse("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"));
    holder.emVideoView.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
        @Override
        public void onPrepared(MediaPlayer mp) {
            holder.emVideoView.start();
        }
    });
    
          
            return convertView;
        }

xml-

    <?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        xmlns:fresco="http://schemas.android.com/apk/res-auto"
        xmlns:EMVideoView="http://schemas.android.com/tools">
        
        <com.devbrackets.android.exomedia.EMVideoView
            android:id="@+id/exovideoview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            EMVideoView:defaultControlsEnabled="true"
         />
    </RelativeLayout>

**Comment by brianwernick** [comment] 2016-02-10 15:27
duplicate of https://github.com/brianwernick/ExoMedia/issues/93

**Closed by brianwernick** 2016-02-10 15:27 UTC
Labels: duplicate

**Comment by bkjbkjbnkj687698698** [comment] 2016-02-10 15:30
@brianwernick its not duplicate ..the issue is because Iam displaying videos in GridView .Its not bcoz of lower Api devices..i am using lollipop

**Comment by bkjbkjbnkj687698698** [comment] 2016-02-10 15:31
does it support showing multiple videos in gridview or listvie?

**Comment by brianwernick** [comment] 2016-02-10 23:35
That isn't something that I directly support (as it is very expensive to have video playback function that way).  See https://github.com/brianwernick/ExoMedia/issues/13
