### ISSUE TITLE
Audio player paused when phone call receive  and not resume when call ends

### ISSUE THREAD

**Issue by arvindkore** [brianwernick/ExoMedia#522] opened 2017-10-12 11:38 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 1.  start player  
 2. make call  

###### Expected Result
player should pause on call receive and resume after call ends
###### Actual Result
player pause but do not  resume

**Comment by brianwernick** [comment] 2017-10-12 15:09
The `AudioPlayer` itself doesn't handle audio focus (NOTE: The `VideoView` does when enabled). What you are seeing is a bug in the library we are using in the demo app that handles the playlist support (PlaylistCore). This is being fixed in the PlaylistCore 2.0 release and was caused by dropping the focus request when the media was paused.

**Closed by brianwernick** 2017-10-12 15:09 UTC
Labels: No Fix Required, Question
