### ISSUE TITLE
Cache issue for some video

### ISSUE THREAD

**Issue by softgears** [brianwernick/ExoMedia#128] opened 2016-03-03 03:15 UTC
I have a recycleview with EMVideoView inside each item. When i try to play video from URL: https://onex1.blob.core.windows.net/posts/3-android-post-item-1456900560.mp4 (recorded on Android camera) it cache and plays well, but when i close app and open it again - video from this URL is wont playing (stuck on preparing stage). 
When i remove app and install it again, all works fine in first launch, in second - stucks. This appears to be a caching issue. This appear to be not for all video. For video like: https://onex1.blob.core.windows.net/posts/3-post-item-1453872771.54758.mp4 (recorded on iPhone camera) it always works fine.
So, is there a way to clear local exo player cache?

**Comment by brianwernick** [comment] 2016-03-03 03:54
Is there any log output from ExoMedia that points to any specific issues?
And are you correctly releasing the EMVideoViews when they are no longer needed. (see #13 for a previous discussion on RecyclerView support)

**Comment by softgears** [comment] 2016-03-04 02:12
This was found in Log output:
``
03-04 12:10:58.348  13115-13347/net.onexapp.onex E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor) could read the stream.
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
            at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor) could read the stream.
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:787)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:718)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
03-04 12:11:02.342  13115-13115/net.onexapp.onex E/ActivityThread﹕ Performing stop of activity that is not resumed: {net.onexapp.onex/net.onexapp.onex.IntroActivity}
    java.lang.RuntimeException: Performing stop of activity that is not resumed: {net.onexapp.onex/net.onexapp.onex.IntroActivity}
            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3325)
            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3406)
            at android.app.ActivityThread.access$1100(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5253)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:948)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:743)

**Comment by softgears** [comment] 2016-03-04 02:27
Video, causing that exception: https://onex1.blob.core.windows.net/posts/3-android-post-item-1457057048.mp4

**Comment by brianwernick** [comment] 2016-03-11 02:49
I'm unable to duplicate this issue with the video you provided.  Would you please answer the following questions to better help us diagnose the issue:

- What ExoMedia version
- What Android Version
- What is the device manufacturer
- Is every EMVideoView being correctly released
- Does this happen immediately, or do you need to scroll through the list for a while before you notice the issue

**Comment by ykorshev** [comment] 2016-03-11 07:42
Tested on ASUS ZenFone 2 with Android 5.0.1. Some times this bug occuer, but some timse not. But if bug occuired, the video becames completly unplayable until the app reinstalled. I guess the problem with invalid local cache management (i think localy cached file became broken and the reader could not obtain metadata from it).

I have the following layout structure:
- Recycler View
- - View Holder
- - - View Pager
- - - - EMVideoView

So, maybe you can advice me a workaround which provides correct EMVideoView releasing in subscribed above layout structure? I am calling .release() method for previously initialized views before populating a new views, or maybe i should call reset locally cached streams or provides correct release procedure.

Thanks.

**Comment by brianwernick** [comment] 2016-03-15 01:55
Thanks for the info. I'll try to reproduce it again when I get some time.

In the meantime, calling `.release()` when populating new views won't perform the cleanup when the activity (or fragment) is destroyed; so you will leak contexts which may cause the issue.

In this case I would have the `RecyclerView.Adapter` keep a list of all the EMVideoViews and in the `onDetachFromWindow()` method call `.release()` on all of them.  Just keep in mind that the `onDetachFromWindow()` isn't called unless you call `recyclerView.setAdapter(null)` in the Activities or Fragments `onDestroy()` method.

**Comment by kinsleykajiva** [comment] 2016-03-30 11:25
hi, i have just started using this library but i seem to see that this library fails to cache for both audio and video stream playback.
I have tried to tweak classes i know to cache the streams but i am still failing to cache the streams in a real device.
Pleas can you help to create a cache that when i use one URL the player should reuse the  created cache to play the video before closure, hence the concept of caching .

Also  this point it may be of  or not related but the player seems to behave better in  the emulator than the real device i don't know if anyone has noticed this ,this a thought....
please can you aid me in the highlighted aspects . Thanks in advance

**Comment by brianwernick** [comment] 2016-03-30 14:57
The ExoPlayer doesn't keep a cache in the normal sense.  Instead it keeps a buffer for the current playing media.  If you need to create an actual cache then you will need to override the RenderBuilders and provide your own DataSource which performs the caching for you. (see https://github.com/brianwernick/ExoMedia/issues/86 and the related changes)

**Comment by kinsleykajiva** [comment] 2016-03-31 08:15
Thanks for the reply  i have been implementing this for HLS and DASH streams but for mp3 and mp4 ...its a different issue bro. i am really stuck as in no where to get help .....

Anyways thanks for the response and time.


________________________________

**Comment by eygraber** [comment] 2016-04-08 18:51
Here's an OkHttp implementation of a `DataSource`. If there is a `Cache` set up with the `OkHttpClient` videos should be cached - https://gist.github.com/eygraber/8e935e19eedc70d2d8e3

**Comment by brianwernick** [comment] 2016-04-30 20:35
@softgears In the current source code I am still having issues reproducing this.  It may have been fixed by any of the many changes for the 3.0 release or by an ExoPlayer update.  I have created a branch ([128](https://github.com/brianwernick/ExoMedia/tree/issue_128)) for testing

**Closed** 2016-05-03 20:34 UTC
Labels: Bug
