### ISSUE TITLE
Exomedia 3.0, gradle dependence is not resolved 

### ISSUE THREAD

**Issue by sujitkjha** [brianwernick/ExoMedia#160] opened 2016-04-05 03:40 UTC
compile 'com.devbrackets.android:exomedia:3.0.0' is not resolved in android studio 1.5.1 ???

**Comment by brianwernick** [comment] 2016-04-05 03:42
Duplicate of #146

**Closed by brianwernick** 2016-04-05 03:42 UTC

**Comment by brianwernick** [comment] 2016-04-15 01:43
There is now a preview release of 3.0.0 (`compile "com.devbrackets.android:exomedia:3.0.0-preview1"`)

**Comment by sujitkjha** [comment] 2016-04-15 07:17
While running demo app so many dependency is not recognized and  so many place it says method need to override some method and all, please have a look to demo app @brianwernick
