### ISSUE TITLE
Occasional incorrect aspect for square video

### ISSUE THREAD

**Issue by denis-trailin-hs** [brianwernick/ExoMedia#281] opened 2016-07-14 22:41 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- ExoMedia version: `3.0.1`
- Device OS version: `6.0.1`
- Devide Manufacturer: `Samsung`
- Device Name: `S6`
###### Reproduction Steps
1. Set up an EMVideo view with the following layout configuration.

```
<android.support.percent.PercentRelativeLayout
    xmlns:EMVideoView="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <FrameLayout
        android:layout_width="match_parent"
        android:background="@color/black"
        android:orientation="vertical">

        <com.devbrackets.android.exomedia.ui.widget.EMVideoView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:minHeight="100dp"
            EMVideoView:useDefaultControls="false"/>
    </FrameLayout>
</android.support.percent.PercentRelativeLayout>
```

Using the following config 

```
  mEMVideoView.setMeasureBasedOnAspectRatioEnabled(true);
  mEMVideoView.setScaleType(ScaleType.FIT_CENTER);
```
1. Open the following file:
   https://dl.dropboxusercontent.com/u/5458508/13017733_608480012662236_1954143025_s.mp4
###### Expected Result

The video render properly like all other videos with this config
###### Actual Result

About half the time the video renders like this:![](http://i.imgur.com/dMwyPk6.jpg)

**Comment by brianwernick** [comment] 2016-09-24 18:35
I've been unable to reproduce this, though I don't have an `S6`. I'm assuming it is a timing issue due to the "About half the time". I'll keep trying to get my hands on an `S6` or similar device to reproduce it, but if you have the time it would be nice if you could look in to the source of the issue.

**Comment by brianwernick** [comment] 2017-01-05 00:13
This seems to be related to #264 where the EMVideoViews size is changed but the scaling isn't updated to match. As such I'm going to close this in favor of that issue.

**Closed by brianwernick** 2017-01-05 00:13 UTC
Labels: Bug
